version: '1.0'
services:
  jupyter:
    build: .
    ports: 
      - 8888:8888
    volumes:
      - /home/igupta/computeenv/tutorials/pytorch_tutorials/workdir:/workdir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
